services: 
  nodeserver: 
    image: szabaldo/mernfolio
    ports: 
      - "80:8080"
    networks: 
      - mn
    depends_on: 
      mysql:
        condition: service_healthy
        restart: true

  mysql: 
    image: mysql
    networks: 
      - mn 
    environment: 
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-proot", "ping", "localhost"]
      interval: 5s
      retries: 5
      timeout: 5s

networks: 
  mn: 
    external: true 
