services: 
  nodeserver: 
    image: szabaldo/mernfolio
    ports: 
      - "80:8080"
    networks: 
      - mf-network
    depends_on: 
      mysqldb:
        condition: service_healthy
        restart: true

  mysqldb: 
    image: mysql
    networks: 
      - mf-network
    environment: 
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-proot", "ping", "-hlocalhost"]
      interval: 5s
      retries: 10
      timeout: 5s

networks: 
  mf-network: 
    external: true 
